### ISSUE TITLE
Implement indexing

### ISSUE THREAD

**Issue by leo60228** [Randdalf/intscript#1]
Assuming the code is placed at 0, and you're using address 10 as an index into the array starting at address 20, you can do the following to execute `arr[idx] = 5`:
```
101,20,10,7
1101,0,5,0
```
The official IntCode programs use a similar pattern to this.

**Comment by Randdalf** [comment]
Good suggestion. Arrays are definitely the next feature I want to implement.

The way the compiler works at the moment, it reserves a cell of memory at the end of the program for each variable. The way I'm imagining arrays working is that they reserve a block of this memory. This does mean that arrays will be a fixed size.

A consequence of fixed-size arrays is that, unlike normal variables, you'd need to declare the array up-front so the compiler knows how much space to allocate.

I'm imagining the subscript operator will just treat whatever value is being subscripted as the address of an array. If it is _actually_ an array, then it can do a little extra to support multi-dimensionality. I'm also thinking it would be useful to add an address-of operator.

For syntax, I was thinking something like this:
```
# Declaration
array a[12][4];

# Indexing
b = a[0][1];

# Address-of
d = &c
```

**Comment by Randdalf** [comment]
I've implemented arrays in https://github.com/Randdalf/intscript/commit/8b031e3b3821b0d640afdb020f571590949950a2. I decided not to implement multi-dimensional arrays, partly because they're not necessary, and partly because doing so would be more difficult.
